### ISSUE TITLE
issue with "Generating embeddable data"

### ISSUE THREAD

**Issue by hihouhou** [vbatoufflet/goverview#2]
Hello Mister Batoufflet,

build: Generating embeddable data...
bindata: Input path 'static/index.html' is not a directory.
result: fail
Makefile:94: recipe for target 'data' failed
make: **\* [data] Error 1

If I move index.html, no error, any idea?

Hihouhou

**Comment by vbatoufflet** [comment]
Hi @hihouhou,

Which version of Go are you using to build it?

**Comment by hihouhou** [comment]
go version go1.3.3 linux/amd64

**Comment by hihouhou** [comment]
Hello,

any idéa?
I can't finish my container :-(

**Comment by hihouhou** [comment]
root@ff799624eef3:/goverview# make
static: Packing script file...
result: ok
static: Applying vendor-specific rules to style file...
result: ok
static: Packing style file...
result: ok
docs: Generating manual page...
result: ok
build: Creating source symlink...
result: ok
build: Generating embeddable data...
bindata: Input path 'static/index.html' is not a directory.
result: fail
Makefile:94: recipe for target 'data' failed
make: **\* [data] Error 1
