### ISSUE TITLE
'services' has no column 'comments_with_extra_info'

### ISSUE THREAD

**Issue by hihouhou** [vbatoufflet/goverview#3]
Hello,

2016/04/08 13:09:16.517875 ERROR: poller: unable to retrieve services from "nagios-xxx" node: Table 'services' has no column 'comments_with_extra_info'

Any idea?

Hihouhou

**Comment by hihouhou** [comment]
FYI:
check-mk-livestatus:
  Installed: 1.1.12-1ubuntu1

**Comment by vbatoufflet** [comment]
The “comments_with_extra_info” column is supported since MK-Livestatus 1.2.2.

I will see if I can make it optional 😉

**Comment by hihouhou** [comment]
perfect!! upgrade appllied but now:
2016/04/08 15:26:17.656537 ERROR: poller: unable to retrieve services from "nagios-test" node: strconv.ParseInt: parsing "No ": invalid syntax
maybe my configuration

**Comment by vbatoufflet** [comment]
Do you have a `No` somewhere in your configuration?
